# See ABOUT.txt for what each option does.
# EDIT_SETTINGS=0 skips splash and launches
# EDIT_SETTINGS=1 shows 3 second splash
EDIT_SETTINGS=1
FLUSH_WAIT=15
INI_PATH=
ICO_PATH=
SOURCE=C:\Program Files (x86)\Steam\userdata\YOUR_STEAM_ID\794600
DEST=C:\Users\Public\Documents\LETITDIE_Backups
HISTORIC_EVERY_DAYS=7
GAME_EXE=BrgGame-Steam.exe
STEAM_EXE=C:\Program Files (x86)\Steam\steam.exe
APPID=794600
